In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
pd.__version__

'1.4.0'

In [3]:
raw = pd.read_csv('db/bucaramanga_transito_accidentes.csv')
raw.sample(10)

,ORDEN,FECHA,AÑO,MES,DÍA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de Vehículo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
32783,32784,2020-11-02T00:00:00.000,2020,11. Noviembre,01. Lunes,CON HERIDOS,0,0,0,0,...,0,0,CARRERA,DANGOND,1899-12-31T13:45:00.000,AGENTES DTB,2 AGENTES DTB,Particular,Diurno,Sin restricción
31821,31822,2020-03-18T00:00:00.000,2020,03. Marzo,03. Miércoles,SOLO DAÑOS,0,1,0,0,...,0,0,AVENIDA EDUARDO SANTOS,SAN ALONSO,1899-12-31T16:00:00.000,AGENTES DTB,1 AGENTES DTB,Particular,Diurno,Sin restricción
15525,15526,2015-11-24T00:00:00.000,2015,11. Noviembre,02. Martes,Solo Daños,0,0,0,0,...,0,0,CALLE,LA CONCORDIA,1899-12-31T22:30:00.000,AGENTES DTB,6 La Concordia,Particular,Nocturno,Sin restricción
16381,16382,2016-02-19T00:00:00.000,2016,02. Febrero,05. Viernes,Solo Daños,0,1,0,0,...,0,0,CARRERA,BOLARQUI,1899-12-31T19:40:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Nocturno,No aplica
11201,11202,2014-10-05T00:00:00.000,2014,10. Octubre,07. Domingo,Solo Daños,0,3,0,0,...,0,0,AUTOPISTA GIRÓN,ZONA INDUSTRIAL,1899-12-31T04:45:00.000,AGENTES DTB,4 Occidental,Particular,Nocturno,No aplica
15795,15796,2015-12-20T00:00:00.000,2015,12. Diciembre,07. Domingo,Con Heridos,0,0,0,1,...,0,0,CARRERA,SAN ALONSO,1899-12-31T10:00:00.000,AGENTES DTB,13 Oriental,Particular,Diurno,Sin restricción
8296,8297,2013-12-21T00:00:00.000,2013,12. Diciembre,06. Sábado,Solo Daños,0,3,0,0,...,0,0,AUTOPISTA FLORIDA BUCARAMANGA,DIAMANTE II,1899-12-31T11:35:00.000,AGENTES POLICIA NACIONAL,10 Provenza,Particular,Diurno,No aplica
17266,17267,2016-05-08T00:00:00.000,2016,05. Mayo,07. Domingo,Solo Daños,0,1,0,0,...,0,0,CALLE,BOLARQUI,1899-12-31T13:10:00.000,AGENTES DTB,12 Cabecera del Llano,Empresa,Diurno,No aplica
15793,15794,2015-12-20T00:00:00.000,2015,12. Diciembre,07. Domingo,Con Heridos,0,1,0,0,...,0,1,ANILLO VIAL,JOSE A. GALAN,1899-12-31T13:00:00.000,AGENTES DTB,5 García Rovira,Particular,Diurno,Sin restricción
3933,3934,2012-11-29T00:00:00.000,2012,11. Noviembre,04. Jueves,Solo Daños,0,0,0,0,...,0,0,CALLE,ZONA INDUSTRIAL,1899-12-31T09:30:00.000,AGENTES POLICIA NACIONAL,4 Occidental,Empresa,Diurno,No aplica

In [4]:
raw.drop(['ORDEN'], axis=1 ,inplace=True)
raw.head(5)

,FECHA,AÑO,MES,DÍA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de Vehículo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
0,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,0,...,0,0,CALLE,MUTIS,1899-12-31T12:15:00.000,AGENTES DTB,17 Mutis,Particular,Diurno,No aplica
1,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Solo Daños,0,1,0,1,0,...,0,0,VIA MATANZA,REGADEROS NORTE,1899-12-31T14:00:00.000,AGENTES DTB,2 Nororiental,Empresa,Diurno,No aplica
2,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Solo Daños,0,0,0,1,0,...,0,0,CARRERA,CABECERA DEL LLANO,1899-12-31T12:00:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Diurno,No aplica
3,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Solo Daños,0,1,0,1,0,...,0,0,CARRERA,NORTE BAJO,1899-12-31T18:30:00.000,AGENTES DTB,3 San Francisco,Particular,Nocturno,No aplica
4,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,0,...,0,0,CARRERA,DANGOND,1899-12-31T00:30:00.000,AGENTES DTB,11 Sur Occidente,Particular,Nocturno,En restricción

In [16]:
raw.describe()

,AÑO,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,BUSETA,BUS,CAMION,VOLQUETA,MOTO,BICICLETA,OTRO
count,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000,34753.000000
mean,2015.956781,0.104797,0.792191,0.062153,0.196818,0.020948,0.044975,0.049319,0.084539,0.014790,0.603804,0.016948,0.020833
std,2.691241,0.337835,0.746755,0.248485,0.431674,0.144213,0.213677,0.220618,0.289552,0.122371,0.650599,0.130630,0.148748
min,2012.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2016.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,2018.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,2021.000000,7.000000,29.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,2.000000,8.000000,3.000000,2.000000

In [6]:
raw['AÑO'].unique()

array([2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

## Corregir categorías de día

In [7]:
raw['DÍA'].unique()

array(['07. Domingo', '01. Lunes', '02. Martes', '03. Miércoles',
       '04. Jueves', '05. Viernes', '06. Sábado', '05. 05. Viernes'],
      dtype=object)

In [8]:
def conv_dia(x):
    if x == "05. 05. Viernes":
        return "05. Viernes"
    else:
        return x

In [9]:
raw['DÍA'] = raw['DÍA'].apply(conv_dia)

In [10]:
raw['DÍA'].unique()

array(['07. Domingo', '01. Lunes', '02. Martes', '03. Miércoles',
       '04. Jueves', '05. Viernes', '06. Sábado'], dtype=object)

## Corregir Categoría Gravedad

In [11]:
def corr_cat_grav(x):
    return x.upper()

In [12]:
raw['GRAVEDAD'] = raw['GRAVEDAD'].apply(corr_cat_grav)
raw['GRAVEDAD'].unique()

array(['CON HERIDOS', 'SOLO DAÑOS', 'CON MUERTOS'], dtype=object)

In [13]:
raw.sample(20)

,FECHA,AÑO,MES,DÍA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de Vehículo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
11507,2014-11-01T00:00:00.000,2014,11. Noviembre,06. Sábado,CON HERIDOS,1,0,0,1,0,...,0,0,AUTOPISTA FLORIDA BUCARAMANGA,DIAMANTE II,1899-12-31T14:30:00.000,AGENTES DTB,10 Provenza,Particular,Diurno,No aplica
13592,2015-05-24T00:00:00.000,2015,05. Mayo,07. Domingo,CON HERIDOS,0,1,0,0,0,...,0,0,DIAGONAL 15,BOLARQUI,1899-12-31T09:05:00.000,AGENTES POLICIA NACIONAL,12 Cabecera del Llano,Particular,Diurno,Sin restricción
31947,2020-05-07T00:00:00.000,2020,05. Mayo,04. Jueves,SOLO DAÑOS,0,1,0,1,0,...,0,0,CARRERA,COMUNEROS,1899-12-31T06:30:00.000,NaN,0,Particular,Diurno,Sin restricción
13054,2015-04-05T00:00:00.000,2015,04. Abril,07. Domingo,SOLO DAÑOS,0,2,0,0,0,...,0,0,CALLE,CENTRO,1899-12-31T17:35:00.000,AGENTES DTB,15 Centro,Empresa,Diurno,No aplica
22853,2017-11-08T00:00:00.000,2017,11. Noviembre,03. Miércoles,CON HERIDOS,0,1,0,0,0,...,0,0,AUTOPISTA NORTE,CAFE MADRID,1899-12-31T13:50:00.000,AGENTES DTB,1 AGENTES DTB,Particular,Diurno,Sin restricción
2191,2012-07-09T00:00:00.000,2012,07. Julio,01. Lunes,SOLO DAÑOS,0,2,0,0,0,...,0,0,CALLE,SOTOMAYOR,1899-12-31T16:30:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Diurno,No aplica
11544,2014-11-05T00:00:00.000,2014,11. Noviembre,03. Miércoles,CON HERIDOS,0,1,0,0,0,...,0,0,CARRERA,ALARCON,1899-12-31T18:24:00.000,AGENTES DTB,3 San Francisco,Particular,Nocturno,Sin restricción
7139,2013-09-10T00:00:00.000,2013,09. Septiembre,02. Martes,SOLO DAÑOS,0,1,0,2,0,...,0,0,CARRERA,GALAN,1899-12-31T11:00:00.000,AGENTES DTB,13 Oriental,Particular,Diurno,No aplica
1478,2012-05-05T00:00:00.000,2012,05. Mayo,06. Sábado,CON HERIDOS,0,1,0,0,0,...,0,0,CALLE,COMUNEROS,1899-12-31T11:16:00.000,AGENTES DTB,3 San Francisco,Empresa,Diurno,Sin restricción
24401,2018-04-06T00:00:00.000,2018,04. Abril,05. Viernes,CON HERIDOS,0,2,0,0,0,...,0,0,CALLE,SOTOMAYOR,1899-12-31T12:10:00.000,AGENTES DTB,0 AGENTES DTB,Particular,Diurno,No aplica
16678,2016-03-16T00:00:00.000,2016,03. Marzo,03. Miércoles,SOLO DAÑOS,0,0,0,0,0,...,0,0,TRANSVERSAL METROPOLITANA,BUCARAMANGA,1899-12-31T12:30:00.000,AGENTES DTB,8 Sur Occidente,Particular,Diurno,No aplica
22516,2017-10-08T00:00:00.000,2017,10. Octubre,07. Domingo,CON HERIDOS,1,0,0,0,0,...,1,0,CALLE,MUTIS,1899-12-31T12:30:00.000,AGENTES DTB,0 AGENTES DTB,Particular,Diurno,No aplica
33171,2021-01-18T00:00:00.000,2021,01. Enero,01. Lunes,CON HERIDOS,0,1,0,0,0,...,0,0,BOULEVAR BOLIVAR,SAN FRANCISCO,1899-12-31T16:00:00.000,AGENTES DTB,1 AGENTES DTB,Particular,Diurno,Sin restricción
18714,2016-10-03T00:00:00.000,2016,10. Octubre,01. Lunes,SOLO DAÑOS,0,1,0,1,0,...,0,0,CARRERA,CABECERA DEL LLANO,1899-12-31T16:00:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Diurno,No aplica
18219,2016-08-15T00:00:00.000,2016,08. Agosto,01. Lunes,CON HERIDOS,1,1,0,0,0,...,0,0,CARRERA,COMUNEROS,1899-12-31T17:55:00.000,AGENTES DTB,3 San Francisco,Particular,Diurno,Sin restricción
10001,2014-06-10T00:00:00.000,2014,06. Junio,02. Martes,CON HERIDOS,1,0,0,0,0,...,0,0,CARRERA,CENTRO,1899-12-31T16:15:00.000,AGENTES POLICIA NACIONAL,15 Centro,Particular,Diurno,Sin restricción
20881,2017-05-11T00:00:00.000,2017,05. Mayo,04. Jueves,CON HERIDOS,1,1,0,0,0,...,0,0,CALLE,CIUDAD BOLIVAR,1899-12-31T19:10:00.000,AGENTES DTB,7 La Ciudadela,Particular,Nocturno,No aplica
3306,2012-10-08T00:00:00.000,2012,10. Octubre,01. Lunes,SOLO DAÑOS,0,2,0,0,0,...,0,0,AVENIDA,CABECERA DEL LLANO,1899-12-31T18:30:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Nocturno,No aplica
12320,2015-01-23T00:00:00.000,2015,01. Enero,05. Viernes,CON HERIDOS,0,1,0,0,0,...,0,0,CALLE,PROVENZA,1899-12-31T09:35:00.000,AGENTES DTB,10 Provenza,Particular,Diurno,Sin restricción
11780,2014-11-29T00:00:00.000,2014,11. Noviembre,06. Sábado,CON HERIDOS,1,0,0,0,0,...,0,0,CALLE,GIRARDOT,1899-12-31T18:30:00.000,AGENTES DTB,4 Occidental,Particular,Nocturno,Sin restricción

In [17]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34753 entries, 0 to 34752
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   FECHA                    34753 non-null  object
 1   AÑO                      34753 non-null  int64
 2   MES                      34753 non-null  object
 3   DÍA                      34753 non-null  object
 4   GRAVEDAD                 34753 non-null  object
 5   PEATON                   34753 non-null  int64
 6   AUTOMOVIL                34753 non-null  int64
 7   CAMPAERO                 34753 non-null  int64
 8   CAMIONETA                34753 non-null  int64
 9   MICRO                    34753 non-null  int64
 10  BUSETA                   34753 non-null  int64
 11  BUS                      34753 non-null  int64
 12  CAMION                   34753 non-null  int64
 13  VOLQUETA                 34753 non-null  int64
 14  MOTO                     34753 non-null  int64
 15  BICICLETA                34753 non-null  int64
 16  OTRO                     34753 non-null  int64
 17  VIA 1                    34753 non-null  object
 18  BARRIO                   34436 non-null  object
 19  HORA                     34752 non-null  object
 20  ENTIDAD                  34510 non-null  object
 21  nombrecomuna             34753 non-null  object
 22  Propietario de Vehículo  34753 non-null  object
 23  DIURNIO/NOCTURNO         34753 non-null  object
 24  HORA RESTRICCION MOTO    34753 non-null  object
dtypes: int64(13), object(12)
memory usage: 6.6+ MB

In [18]:
raw['MICRO'] = raw['MICRO']+raw['BUSETA']
raw.sample(10)

,FECHA,AÑO,MES,DÍA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de Vehículo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
31265,2020-01-22T00:00:00.000,2020,01. Enero,03. Miércoles,SOLO DAÑOS,0,2,0,0,0,...,0,0,CARRERA,LA CONCORDIA,1899-12-31T13:20:00.000,AGENTES DTB,0 AGENTES DTB,Particular,Diurno,Sin restricción
20117,2017-02-25T00:00:00.000,2017,02. Febrero,06. Sábado,SOLO DAÑOS,0,1,0,0,0,...,0,0,CALLE,RICAURTE,1899-12-31T11:50:00.000,AGENTES DTB,6 La Concordia,Particular,Diurno,No aplica
19331,2016-12-02T00:00:00.000,2016,12. Diciembre,05. Viernes,CON HERIDOS,0,0,0,1,0,...,0,0,CALLE,ALFONSO LOPEZ,1899-12-31T18:05:00.000,AGENTES DTB,5 García Rovira,Particular,Nocturno,No aplica
19027,2016-11-03T00:00:00.000,2016,11. Noviembre,04. Jueves,CON HERIDOS,0,0,0,1,0,...,0,0,AUTOPISTA NORTE,MIRAMAR,1899-12-31T19:00:00.000,AGENTES DTB,1 Norte,Empresa,Nocturno,Sin restricción
24515,2018-04-16T00:00:00.000,2018,04. Abril,01. Lunes,CON HERIDOS,0,0,0,1,0,...,0,0,CARRERA,SAN RAFAEL,1899-12-31T17:45:00.000,AGENTES DTB,1 AGENTES DTB,Particular,Diurno,Sin restricción
4223,2012-12-22T00:00:00.000,2012,12. Diciembre,06. Sábado,CON HERIDOS,1,0,0,0,0,...,0,0,CALLE,CAMPO HERMOSO,1899-12-31T05:30:00.000,AGENTES DTB,5 García Rovira,Particular,Nocturno,Sin restricción
30715,2019-11-26T00:00:00.000,2019,11. Noviembre,02. Martes,CON HERIDOS,0,0,0,0,0,...,0,0,TRANSVERSAL ORIENTAL,PORTON DEL TEJAR,6:45:00a.m.,AGENTES DTB,2 AGENTES DTB,Particular,Diurno,Sin restricción
832,2012-03-10T00:00:00.000,2012,03. Marzo,06. Sábado,SOLO DAÑOS,0,2,0,0,0,...,0,0,CARRERA,CONUCOS,1899-12-31T06:20:00.000,AGENTES DTB,12 Cabecera del Llano,Particular,Diurno,No aplica
18054,2016-07-29T00:00:00.000,2016,07. Julio,05. Viernes,SOLO DAÑOS,0,1,0,1,0,...,0,0,CARRERA,ALFONSO LOPEZ,1899-12-31T09:30:00.000,AGENTES DTB,5 García Rovira,Particular,Diurno,No aplica
10858,2014-09-02T00:00:00.000,2014,09. Septiembre,02. Martes,CON HERIDOS,0,0,0,0,0,...,0,0,CALLE,COMUNEROS,1899-12-31T12:10:00.000,AGENTES DTB,3 San Francisco,Particular,Diurno,Sin restricción

In [19]:
raw['MICRO'].rename('MICRO&BUSETA')

0        0
1        0
2        0
3        0
4        0
        ..
34748    0
34749    0
34750    0
34751    0
34752    0
Name: MICRO&BUSETA, Length: 34753, dtype: int64

In [20]:
raw.pop('BUSETA')

0        0
1        0
2        0
3        0
4        0
        ..
34748    0
34749    0
34750    0
34751    0
34752    0
Name: BUSETA, Length: 34753, dtype: int64

In [22]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34753 entries, 0 to 34752
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   FECHA                    34753 non-null  object
 1   AÑO                      34753 non-null  int64
 2   MES                      34753 non-null  object
 3   DÍA                      34753 non-null  object
 4   GRAVEDAD                 34753 non-null  object
 5   PEATON                   34753 non-null  int64
 6   AUTOMOVIL                34753 non-null  int64
 7   CAMPAERO                 34753 non-null  int64
 8   CAMIONETA                34753 non-null  int64
 9   MICRO                    34753 non-null  int64
 10  BUS                      34753 non-null  int64
 11  CAMION                   34753 non-null  int64
 12  VOLQUETA                 34753 non-null  int64
 13  MOTO                     34753 non-null  int64
 14  BICICLETA                34753 non-null  int64
 15  OTRO                     34753 non-null  int64
 16  VIA 1                    34753 non-null  object
 17  BARRIO                   34436 non-null  object
 18  HORA                     34752 non-null  object
 19  ENTIDAD                  34510 non-null  object
 20  nombrecomuna             34753 non-null  object
 21  Propietario de Vehículo  34753 non-null  object
 22  DIURNIO/NOCTURNO         34753 non-null  object
 23  HORA RESTRICCION MOTO    34753 non-null  object
dtypes: int64(12), object(12)
memory usage: 6.4+ MB

In [31]:
raw = raw.rename(columns={'MICRO':'MICRO_BUSETA'})

In [32]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34753 entries, 0 to 34752
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   FECHA                    34753 non-null  object
 1   AÑO                      34753 non-null  int64
 2   MES                      34753 non-null  object
 3   DÍA                      34753 non-null  object
 4   GRAVEDAD                 34753 non-null  object
 5   PEATON                   34753 non-null  int64
 6   AUTOMOVIL                34753 non-null  int64
 7   CAMPAERO                 34753 non-null  int64
 8   MICRO_BUSETA             34753 non-null  int64
 9   BUS                      34753 non-null  int64
 10  CAMION                   34753 non-null  int64
 11  VOLQUETA                 34753 non-null  int64
 12  MOTO                     34753 non-null  int64
 13  BICICLETA                34753 non-null  int64
 14  OTRO                     34753 non-null  int64
 15  VIA 1                    34753 non-null  object
 16  BARRIO                   34436 non-null  object
 17  HORA                     34752 non-null  object
 18  ENTIDAD                  34510 non-null  object
 19  nombrecomuna             34753 non-null  object
 20  Propietario de Vehículo  34753 non-null  object
 21  DIURNIO/NOCTURNO         34753 non-null  object
 22  HORA RESTRICCION MOTO    34753 non-null  object
dtypes: int64(11), object(12)
memory usage: 6.1+ MB

In [26]:
raw['CAMPAERO'] = raw['CAMPAERO'] + raw['CAMIONETA']
raw.pop('CAMIONETA')
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34753 entries, 0 to 34752
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   FECHA                    34753 non-null  object
 1   AÑO                      34753 non-null  int64
 2   MES                      34753 non-null  object
 3   DÍA                      34753 non-null  object
 4   GRAVEDAD                 34753 non-null  object
 5   PEATON                   34753 non-null  int64
 6   AUTOMOVIL                34753 non-null  int64
 7   CAMPAERO                 34753 non-null  int64
 8   MICRO                    34753 non-null  int64
 9   BUS                      34753 non-null  int64
 10  CAMION                   34753 non-null  int64
 11  VOLQUETA                 34753 non-null  int64
 12  MOTO                     34753 non-null  int64
 13  BICICLETA                34753 non-null  int64
 14  OTRO                     34753 non-null  int64
 15  VIA 1                    34753 non-null  object
 16  BARRIO                   34436 non-null  object
 17  HORA                     34752 non-null  object
 18  ENTIDAD                  34510 non-null  object
 19  nombrecomuna             34753 non-null  object
 20  Propietario de Vehículo  34753 non-null  object
 21  DIURNIO/NOCTURNO         34753 non-null  object
 22  HORA RESTRICCION MOTO    34753 non-null  object
dtypes: int64(11), object(12)
memory usage: 6.1+ MB

In [33]:
raw = raw.rename(columns={'CAMPAERO': 'CAMPERO_CAMIONETA'})
raw = raw.rename(columns={'nombrecomuna':'COMUNA', 'Propietario de Vehículo':'TIPO_PROPIETARIO'})
raw.info()

In [37]:
raw['MES'].unique()

array(['01. Enero', '02. Febrero', '03. Marzo', '04. Abril', '05. Mayo',
       '06. Junio', '07. Julio', '08. Agosto', '09. Septiembre',
       '10. Octubre', '11. Noviembre', '12. Diciembre'], dtype=object)